CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" varchar(20) NOT NULL
);

CREATE TABLE "departments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "status" varchar(20) NOT NULL,
  "manager_id" bigint
);

CREATE TABLE "employees" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint UNIQUE NOT NULL,
  "employee_code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "phone" varchar(15),
  "joining_date" date NOT NULL,
  "department_id" bigint NOT NULL,
  "status" varchar(20) NOT NULL
);

CREATE TABLE "leave_types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "yearly_days" int NOT NULL,
  "status" varchar(20) NOT NULL
);

CREATE TABLE "leave_balances" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" bigint NOT NULL,
  "leave_type_id" bigint NOT NULL,
  "year" int NOT NULL,
  "total_days" int NOT NULL,
  "used_days" int NOT NULL,
  "version" bigint NOT NULL DEFAULT 0
);

CREATE TABLE "leave_requests" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" bigint NOT NULL,
  "leave_type_id" bigint NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "days" int NOT NULL,
  "reason" text,
  "status" varchar(20) NOT NULL,
  "reviewed_by" bigint,
  "reviewed_at" timestamp,
  "rejection_reason" text,
  "created_at" timestamp NOT NULL
);

CREATE UNIQUE INDEX ON "leave_balances" ("employee_id", "leave_type_id", "year");

ALTER TABLE "departments" ADD FOREIGN KEY ("manager_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leave_balances" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leave_balances" ADD FOREIGN KEY ("leave_type_id") REFERENCES "leave_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leave_requests" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leave_requests" ADD FOREIGN KEY ("leave_type_id") REFERENCES "leave_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leave_requests" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Run this migration once for databases created before leave_balances.version was added.
ALTER TABLE "leave_balances" ADD COLUMN IF NOT EXISTS "version" bigint;
UPDATE "leave_balances" SET "version" = 0 WHERE "version" IS NULL;
ALTER TABLE "leave_balances" ALTER COLUMN "version" SET DEFAULT 0;
ALTER TABLE "leave_balances" ALTER COLUMN "version" SET NOT NULL;

-- Run this migration once for databases created before leave_requests.version was added.
ALTER TABLE "leave_requests" ADD COLUMN IF NOT EXISTS "version" bigint;
UPDATE "leave_requests" SET "version" = 0 WHERE "version" IS NULL;
ALTER TABLE "leave_requests" ALTER COLUMN "version" SET DEFAULT 0;
ALTER TABLE "leave_requests" ALTER COLUMN "version" SET NOT NULL;
